[package]
name = "auto-drive-edge"
version = "0.1.0"
edition = "2024"

[dependencies]
the-beginner-car-tcp-protocol = { path = "../firmware/the-beginner-car-wifi-firmware/api/the-beginner-car-tcp-protocol" }
gilrs = { version = "0.11.2", default-features = false, features = ["xinput"] }
metrics = "0.24.6"
postcard = { version = "1.1.3", features = ["use-std"] }
serde = { version = "1.0.229", features = ["derive"] }
tokio = { version = "1", features = [
  "net",
  "io-util",
  "macros",
  "rt-multi-thread",
  "time",
] }
toml = "1.1.8"
opentelemetry-otlp = { version = "0.33.1", features = ["grpc-tonic", "trace", "metrics"] }
warp = "0.4.3"
opentelemetry = "0.33.1"
opentelemetry_sdk = "0.33.1"
