[package]
name = "common-firmware"
version = "0.1.0"
edition = "2024"

[dependencies]
esp-idf-svc = { version = "0.52.1", features = ["critical-section", "embassy-time-driver", "embassy-sync", "std", "experimental", "alloc", "default"] }
esp-idf-sys = "0.37.2"
anyhow = "1.0.104"
postcard = { version = "1.1.3", features = ["alloc"] }
serde = "1.0.229"
crc = "3.4.0"
ws2812-spi = { version = "0.5", features = ["mosi_idle_high"] }
smart-leds-trait = "0.3.2"
futures = "0.3.34"

[build-dependencies]
embuild = "0.33"
