[package]
name = "auto-drive-the-beginner-firmware"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "main"
path = "src/main.rs"
harness = false

[dependencies]
anyhow = "1.0.104"
wasmtime = "48.0.1"
wasmtime-wasi = "48.0.1"
wit-bindgen = "0.61.1"
log = "0.4"
esp-idf-svc = { version = "0.52.1", features = ["critical-section", "embassy-time-driver", "embassy-sync", "std", "experimental", "alloc", "default"] }
embassy-time = { version = "0.5", features = ["generic-queue-8"] }
embedded-svc = "0.29.0"
embedded-dht-rs = { version = "0.5.0", features = ["dht11"] }
dotenvy_macro = "0.15.7"

[build-dependencies]
embuild = "0.33"

[[package.metadata.esp-idf-sys.extra_components]]
remote_component = { name = "espressif/mdns", version = "1.8.2" }
